import os

ALIYUN_PREFIX = os.environ["ALIYUN_PREFIX"]
ALIYUN_ACCESSKEY_ID = os.environ["ALIYUN_ACCESSKEY_ID"]
ALIYUN_ACCESSKEY_SECRET = os.environ["ALIYUN_ACCESSKEY_SECRET"]
ALIYUN_REGION = os.environ["ALIYUN_REGION"]
OSS_BUCKET = os.environ["OSS_BUCKET"]
OSS_PREFIX = os.environ["OSS_PREFIX"]
